modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_github}/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_github}"
#logoFile=""
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="sable"
    type="required"
    versionRange="[${sable_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="voltaic"
    type="optional"
    versionRange="[${voltaic_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="electrodynamics"
    type="optional"
    versionRange="[${electrodynamics_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="nuclearscience"
    type="optional"
    versionRange="[${nuclear_science_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="ballistix"
    type="optional"
    versionRange="[${ballistix_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="pneumaticcraft"
    type="optional"
    versionRange="[${pneumaticcraft_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="moretnt"
    type="optional"
    versionRange="[${more_fun_tnts_version},)"
    ordering="AFTER"
    side="BOTH"
